apiVersion: v1
kind: Pod
metadata:
  name: pod-time-server
  labels:
    app: pod-time-server
spec:
  containers:
  - name: time-server-container
    image: clusterminator/time-server:2.0
    ports:
    - containerPort: 5000
